package com.ai.service;

import com.ai.dto.DesignRequestDto;
import com.ai.dto.GeneratedUiDto;
import com.ai.service.llm.LlmService;
import com.ai.util.HtmlExtractor;
import lombok.RequiredArgsConstructor;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Service
@RequiredArgsConstructor
public class ImageToCodeService {

    private final LlmService llmService;
    private final TempFileCleanupService cleanupService;

    public GeneratedUiDto generateFromImage(MultipartFile file, String style) throws IOException {
        String cleanHtml = generateImagePreview(file, style);
        return buildZipResponse(cleanHtml, file.getOriginalFilename(), 0, "upload", file.getOriginalFilename());
    }

    @Cacheable(value = "htmlPreviewCache", key = "#root.args[0].originalFilename + '_' + #style")
    public String generateImagePreview(MultipartFile file, String style) throws IOException {
        String rawResponse = llmService.generateCodeFromImage(
                file.getBytes(),
                file.getContentType(),
                style
        );
        return HtmlExtractor.extractCleanHtml(rawResponse);
    }

    public GeneratedUiDto generateFromDesign(DesignRequestDto request) {
        String cleanHtml = generateDesignPreview(request);
        return buildZipResponse(cleanHtml, "generated-design", request.blocks().size(), "design", null);
    }

    @Cacheable(value = "htmlPreviewCache", key = "'design_' + T(java.util.Objects).hashCode(#request)")
    public String generateDesignPreview(DesignRequestDto request) {
        String rawResponse = llmService.generateCodeFromDesign(request);
        return HtmlExtractor.extractCleanHtml(rawResponse);
    }

    private GeneratedUiDto buildZipResponse(String html, String baseName, int blockCount, String mode, String originalFileName) {
        String safeName = baseName == null ? "generated-ui" :
                baseName.replaceAll("[^a-zA-Z0-9]", "_");

        try {
            Path tempDir = Files.createTempDirectory("generated-ui-");

            Path htmlFile = tempDir.resolve("index.html");
            Files.writeString(htmlFile, html, StandardCharsets.UTF_8);

            Path zipFile = tempDir.resolve(safeName + ".zip");
            try (FileOutputStream fos = new FileOutputStream(zipFile.toFile());
                 ZipOutputStream zos = new ZipOutputStream(fos)) {

                ZipEntry htmlEntry = new ZipEntry("index.html");
                zos.putNextEntry(htmlEntry);
                zos.write(html.getBytes(StandardCharsets.UTF_8));
                zos.closeEntry();

                ZipEntry cssEntry = new ZipEntry("style.css");
                zos.putNextEntry(cssEntry);
                String cssContent = """
                        body { font-family: Arial, sans-serif; padding: 20px; background-color: #f9fafb; }
                        h1, h2, h3 { color: #4f46e5; }
                        button { background-color: #4f46e5; color: white; border: none; padding: 8px 16px; border-radius: 6px; cursor: pointer; }
                        a { color: #4f46e5; text-decoration: none; }
                        """;
                zos.write(cssContent.getBytes(StandardCharsets.UTF_8));
                zos.closeEntry();

                ZipEntry jsEntry = new ZipEntry("script.js");
                zos.putNextEntry(jsEntry);
                String jsContent = "console.log('Generated by Vision2Markup');";
                zos.write(jsContent.getBytes(StandardCharsets.UTF_8));
                zos.closeEntry();

                ZipEntry readmeEntry = new ZipEntry("README.md");
                zos.putNextEntry(readmeEntry);

                String readmeContent = String.format("""
                        # Vision2Markup - Generated Web App

                        Mode: %s
                        Uploaded File: %s
                        Number of Blocks: %d
                        Generation Date: %s

                        ## Contents
                        - index.html : main HTML file
                        - style.css  : default styling
                        - script.js  : default JavaScript
                        - README.md  : this file

                        ## How to Deploy
                        1. Extract the ZIP file.
                        2. Open `index.html` in a browser to preview.
                        3. Host the folder on any static web server (GitHub Pages, Netlify, Vercel) to deploy online.

                        ## Notes
                        - Modify `style.css` to customize design.
                        - Modify `script.js` to add interactivity.
                        - Generated HTML is AI-created and may need minor adjustments.
                        """,
                        mode,
                        originalFileName == null ? "N/A" : originalFileName,
                        blockCount,
                        LocalDateTime.now()
                );

                zos.write(readmeContent.getBytes(StandardCharsets.UTF_8));
                zos.closeEntry();
            }

            cleanupService.registerTempFile(zipFile);

            return new GeneratedUiDto(html, zipFile.toAbsolutePath().toString());

        } catch (IOException e) {
            throw new RuntimeException("Failed to generate ZIP", e);
        }
    }
}